#!/bin/bash
#PBS -N GMX_MD
#PBS -j oe
#PBS -l select=8:ncpus=8:mpiprocs=8
#PBS -l walltime=00:20:00

# host: jade.cines.fr
# queuing system: SGE

# set this to the same value as walltime; mdrun will stop cleanly
# at 0.99 * WALL_HOURS 
WALL_HOURS=0.33

# deffnm line is possibly modified by gromacs.setup
# (leave it as it is in the template)
DEFFNM=md

TPR=${DEFFNM}.tpr
OUTPUT=${DEFFNM}.out
PDB=${DEFFNM}.pdb

# use this for, e.g. optimum number of pme nodes (-npme N)
MDRUN_OPTIONS="-npme 28"

echo "--- PBS_NODEFILE"
cat $PBS_NODEFILE
cd $PBS_O_WORKDIR

export MPI_GROUP_MAX=1024

#module load gromacs

# use hard coded path for time being
GMXBIN="/opt/software/SGI/gromacs/4.0.3/bin"

MPIRUN=/usr/pbs/bin/mpiexec
APPLICATION=$GMXBIN/mdrun_mpi


$MPIRUN $APPLICATION -step 1000 -deffnm ${DEFFNM} -s ${TPR} -c ${PDB} -cpi \
                     $MDRUN_OPTIONS \
                     -maxh ${WALL_HOURS} > $OUTPUT

exit 0
