# Sun Gridengine runscipt for 'neuron'
#$ -N GMX_MD
#$ -S /bin/bash
#$ -pe openmpi_singlenode 8
#$ -q all.q -cwd -r y -j y -V

# host: neuron.bioch.ox.ac.uk
# queuing system: SGE

DEFFNM=md

TPR=${DEFFNM}.tpr
OUTPUT=${DEFFNM}.out
PDB=${DEFFNM}.pdb

MDRUN_OPTS=""

# JOB_ARRAY_PLACEHOLDER

MPIRUN=/packages/opt/openmpi-1.2.8/intel9/bin/mpirun
APPLICATION=/packages/opt/gromacs-4.0.3/intel9/fftw-3.2/openmpi-1.2.8/bin/mdrun_mpi

$MPIRUN $APPLICATION -step 1000 -deffnm ${DEFFNM} -s ${TPR} -c ${PDB} \
                     -cpi $MDRUN_OPTS  >$OUTPUT 2>&1
rc=$?


exit $rc
