#!/usr/bin/env python
#$ -N bulk
#$ -S /usr/bin/python
#$ -v PYTHONPATH=/home/oliver/Library/python-lib
#$ -v LD_LIBRARY_PATH=/opt/intel/cmkl/8.0/lib/32:/opt/intel/itc60/slib:/opt/intel/ipp41/ia32_itanium/sharedlib:/opt/intel/ipp41/ia32_itanium/sharedlib/linux32:/opt/intel/fc/9.0/lib:/opt/intel/cc/9.0/lib
#$ -r n
#$ -j y
# The next line is IMPORTANT when you are using the default for Job(startdir=None)
#$ -cwd

from staging.SunGridEngine import Job


# fake it
import os
os.environ['JOB_NAME'] = 'testing'
os.environ['JOB_ID'] = '999999'
os.environ['SGE_TASK_ID'] = '1'

t = open('my.fake','w')
t.write('Sinnloser Input\n\n')
t.close()

job = Job(inputfiles=dict( fakeit = 'my.fake'),
          outputfiles=dict(txt = 'output/*.txt'),
          variables=dict(normalize = True))

print "input: %(fakeit)s" % job.filenames
print "normalize = %(normalize)s" % job.variables


job.stage()
F = job.filenames  # use F[key] to reference filenames from inputfiles or outputfiles
V = job.variables  # and V[key] for the variables

# your python script here...
print "input: %(fakeit)s" % F
print "normalize = %(normalize)s" % V

t = open('output/A.txt','w')
t.write('A file')
t.close()
t = open('output/B.txt','w')
t.write('Fucking hell!\n')
t.close()
print 'Wrote A and B files'


job.unstage()
job.cleanup()   # removes stage dir, careful!
