name: CI

on:
  # run every month on day 14 and 28 at 4:44 UTC
  schedule:
    - cron: "44 4 14,28 * *"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        gromacs-version: ["2021.1"]
        # Test other GROMACS versions selectively on a recent Python.
        # On macOS only test one GROMACS version and two Python versions
        # to keep the testing matrix manageable.
        exclude:
          - os: macOS-latest
            python-version: "3.6"
          - os: macOS-latest
            python-version: "3.7"
          - os: macOS-latest
            python-version: "3.8"
          - os: macOS-latest
            python-version: "3.9"
          - os: macOS-latest
            python-version: "3.10"
        include:
          - os: ubuntu-latest
            python-version: "2.7"
            gromacs-version: "4.6.5"    
          - os: ubuntu-latest
            python-version: "3.11"
            gromacs-version: "4.6.5"
          - os: ubuntu-latest
            python-version: "3.11"
            gromacs-version: "2018.6"
          - os: ubuntu-latest
            python-version: "3.11"
            gromacs-version: "2019.1"
          - os: ubuntu-latest
            python-version: "3.11"
            gromacs-version: "2020.6"
          - os: ubuntu-latest
            python-version: "3.11"
            gromacs-version: "2022.4"
          - os: ubuntu-latest
            python-version: "3.11"
            gromacs-version: "2023.1"
            

    env:
      MPLBACKEND: agg
        

    steps:
    - uses: actions/checkout@v3

    - name: micromamba environment and package installation (Python ${{ matrix.python-version }})
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ci/conda-envs/test_env.yaml
        condarc: |
           channels:
              - conda-forge
              - bioconda
           channel_priority: flexible         
        cache-downloads: true
        cache-environment: true
        create-args: >-
           python=${{ matrix.python-version }}.*=*_cpython

    - name: Python version information ${{ matrix.python-version }}
      run: |
         python -c "import sys; print(sys.version)"                

    - name: micromamba environment information
      run: |
         micromamba info
         micromamba list

    - name: Install pytest and plugins
      run: |
         micromamba install pytest pytest-pep8 pytest-cov codecov

    - name: Install GROMACS (${{ matrix.gromacs-version }})
      # UGLY HACK/FIX (probably to issues with bioconda packages)
      # - For 3.9, micromamba insists on using pypy 3.9 (and --py-pin does not help).
      # - For 2.7 macOS, numkit would get uninstalled.
      # We can't freeze because then it's not possible to install older GROMACS versions from bioconda. 
      run: |
         micromamba install 'gromacs==${{ matrix.gromacs-version }}' pocl numkit python=${{ matrix.python-version }}.*=*_cpython

    - name: Install package (with no dependencies)
      run: |
        python -m pip install --no-deps .

    - name: Run tests
      run: |
        pytest -v --disable-pytest-warnings --durations=20 --low-performance --cov=gromacs --cov-report=xml --color=yes ./tests

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
        file: ./coverage.xml
        fail_ci_if_error: false
